version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - myapp_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
       DATABASE_PORT: 5432
       DATABASE_HOST: db
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - myapp_network

volumes:
  db:
networks:
  myapp_network:

